# -*- coding: utf-8 -*-
"""etl_project_gdp_with_sql.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kKZL12BJ6CWMsb8zb5-f8mWI3yESHoxj
"""

import sqlite3
from datetime import datetime

import pandas as pd
import requests
from bs4 import BeautifulSoup


# ============================================================
# Configuration
# ============================================================

DB_PATH = "World_Economies.db"
LOG_FILE = "etl_project_log.txt"

RAW_JSON = "Countries_by_GDP_raw.json"
TRANSFORMED_JSON = "Countries_by_GDP.json"


# ============================================================
# Logging
# ============================================================

def log(message: str) -> None:
    """
    Write ETL log message with timestamp.

    Args:
        message (str): Log message.
    """
    # ETL 각 단계의 시작과 끝을 파일에 append 방식으로 기록
    timestamp = datetime.now().strftime("%Y-%B-%d-%H-%M-%S")
    with open(LOG_FILE, "a", encoding="utf-8") as file:
        file.write(f"{timestamp}, {message}\n")


# ============================================================
# 1회성 Country - Region 테이블 생성
# ============================================================

def create_country_region_table() -> None:
    """
    Create Country_Region table with hard-coded country-region mapping.
    """
    # Region 분석을 위해 국가-대륙 매핑 테이블을 미리 생성
    log("CREATE Country_Region START")

    rows = [
        # Americas
        ("United States", "Americas"), ("Canada", "Americas"),
        ("Mexico", "Americas"), ("Brazil", "Americas"),
        ("Argentina", "Americas"), ("Chile", "Americas"),
        ("Colombia", "Americas"), ("Peru", "Americas"),
        ("Venezuela", "Americas"), ("Ecuador", "Americas"),
        ("Bolivia", "Americas"), ("Paraguay", "Americas"),
        ("Uruguay", "Americas"), ("Panama", "Americas"),
        ("Costa Rica", "Americas"), ("Guatemala", "Americas"),
        ("Honduras", "Americas"), ("El Salvador", "Americas"),
        ("Nicaragua", "Americas"), ("Dominican Republic", "Americas"),
        ("Cuba", "Americas"), ("Haiti", "Americas"),
        ("Jamaica", "Americas"),

        # Europe
        ("Germany", "Europe"), ("United Kingdom", "Europe"),
        ("France", "Europe"), ("Italy", "Europe"),
        ("Spain", "Europe"), ("Netherlands", "Europe"),
        ("Belgium", "Europe"), ("Switzerland", "Europe"),
        ("Austria", "Europe"), ("Sweden", "Europe"),
        ("Norway", "Europe"), ("Denmark", "Europe"),
        ("Finland", "Europe"), ("Ireland", "Europe"),
        ("Poland", "Europe"), ("Czech Republic", "Europe"),
        ("Slovakia", "Europe"), ("Hungary", "Europe"),
        ("Romania", "Europe"), ("Bulgaria", "Europe"),
        ("Greece", "Europe"), ("Portugal", "Europe"),
        ("Ukraine", "Europe"), ("Russia", "Europe"),

        # Asia
        ("China", "Asia"), ("Japan", "Asia"),
        ("India", "Asia"), ("South Korea", "Asia"),
        ("Indonesia", "Asia"), ("Thailand", "Asia"),
        ("Vietnam", "Asia"), ("Malaysia", "Asia"),
        ("Philippines", "Asia"), ("Bangladesh", "Asia"),
        ("Pakistan", "Asia"), ("Sri Lanka", "Asia"),
        ("Nepal", "Asia"), ("Kazakhstan", "Asia"),
        ("Uzbekistan", "Asia"), ("Taiwan", "Asia"),
        ("Hong Kong", "Asia"), ("Singapore", "Asia"),

        # Middle East
        ("Saudi Arabia", "Middle East"),
        ("United Arab Emirates", "Middle East"),
        ("Israel", "Middle East"), ("Turkey", "Middle East"),
        ("Iran", "Middle East"), ("Iraq", "Middle East"),
        ("Qatar", "Middle East"), ("Kuwait", "Middle East"),
        ("Oman", "Middle East"), ("Jordan", "Middle East"),
        ("Lebanon", "Middle East"), ("Yemen", "Middle East"),

        # Africa
        ("South Africa", "Africa"), ("Nigeria", "Africa"),
        ("Egypt", "Africa"), ("Algeria", "Africa"),
        ("Morocco", "Africa"), ("Tunisia", "Africa"),
        ("Ethiopia", "Africa"), ("Kenya", "Africa"),
        ("Ghana", "Africa"), ("Angola", "Africa"),

        # Oceania
        ("Australia", "Oceania"), ("New Zealand", "Oceania"),
        ("Papua New Guinea", "Oceania"), ("Fiji", "Oceania"),
    ]

    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    cur.execute("""
        CREATE TABLE IF NOT EXISTS Country_Region (
            Country TEXT PRIMARY KEY,
            Region TEXT
        )
    """)

    # 동일한 매핑을 유지하기 위해 매번 초기화
    cur.execute("DELETE FROM Country_Region")
    cur.executemany(
        "INSERT INTO Country_Region VALUES (?, ?)",
        rows
    )

    conn.commit()
    conn.close()

    log("CREATE Country_Region END")


# ============================================================
# Extract
# ============================================================

def extract(url: str, output_json: str) -> None:
    """
    Extract raw GDP table from Wikipedia and save as JSON.
    """
    log("EXTRACT START")

    headers = {"User-Agent": "Mozilla/5.0"}
    response = requests.get(url, headers=headers)
    response.raise_for_status()

    soup = BeautifulSoup(response.text, "html.parser")

    # Wikipedia GDP 테이블은 wikitable class 사용
    table = soup.find("table", class_="wikitable")
    rows = table.find("tbody").find_all("tr")

    records = []
    for row in rows:
        # th와 td를 함께 수집 (헤더/국가명 구조 차이 때문)
        cells = row.find_all(["th", "td"])
        records.append(
            [cell.get_text(strip=True) for cell in cells]
        )

    header = records[0]
    data = records[1:]

    # 행마다 컬럼 개수가 다른 경우를 대비해 길이 보정
    max_len = max(len(row) for row in records)

    def normalize(row):
        return row + [None] * (max_len - len(row))

    header = normalize(header)
    data = [normalize(row) for row in data]

    df = pd.DataFrame(data, columns=header)

    df.to_json(
        output_json,
        orient="records",
        force_ascii=False,
        indent=2
    )

    log("EXTRACT END")


# ============================================================
# Transform
# ============================================================

def transform(input_json: str, output_json: str) -> None:
    """
    Transform raw GDP data and save cleaned JSON.
    """
    log("TRANSFORM START")

    df_raw = pd.read_json(input_json)

    # Wikipedia 테이블 기준:
    # 0번째 컬럼: Country / 1번째 컬럼: IMF GDP
    df = df_raw.iloc[:, [0, 1]].copy()
    df.columns = ["Country", "IMF"]

    # 국가명에 포함된 각주([1], [a] 등) 제거
    df["Country"] = (
        df["Country"]
        .astype(str)
        .str.replace(r"\[.*?\]", "", regex=True)
        .str.strip()
    )

    # 숫자가 아닌 GDP 표현 제거
    df["IMF"] = (
        df["IMF"]
        .astype(str)
        .str.replace(",", "", regex=False)
        .replace(["—", "N/a", "—N/a"], pd.NA)
    )

    df["IMF"] = pd.to_numeric(df["IMF"], errors="coerce")
    df = df.dropna(subset=["IMF"])

    # IMF 데이터 단위: million USD -> billion USD 변환
    df["GDP_USD_billion"] = (df["IMF"] / 1000).round(2)

    # GDP 내림차순 정렬
    df = df.sort_values("GDP_USD_billion", ascending=False)

    df[["Country", "GDP_USD_billion"]].to_json(
        output_json,
        orient="records",
        force_ascii=False,
        indent=2
    )

    log("TRANSFORM END")


# ============================================================
# Load
# ============================================================

def load(transformed_json: str) -> None:
    """
    Load transformed GDP data into SQLite.
    """
    log("LOAD START")

    df = pd.read_json(transformed_json)

    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    cur.execute("""
        CREATE TABLE IF NOT EXISTS Countries_by_GDP (
            Country TEXT,
            GDP_USD_billion REAL
        )
    """)

    # 데이터만 갱신하고 테이블 구조는 유지
    cur.execute("DELETE FROM Countries_by_GDP")

    df.to_sql(
        "Countries_by_GDP",
        conn,
        if_exists="append",
        index=False
    )

    conn.commit()
    conn.close()

    log("LOAD END")


# ============================================================
# Query
# ============================================================

def run_queries() -> None:
    """
    Execute required SQL queries and print results.
    """
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    print("\n[ GDP ≥ 100B USD ]")
    for row in cur.execute("""
        SELECT Country, GDP_USD_billion
        FROM Countries_by_GDP
        WHERE GDP_USD_billion >= 100
        ORDER BY GDP_USD_billion DESC
    """):
        print(row)

    print("\n[ Region별 Top5 GDP 평균 ]")
    for row in cur.execute("""
        SELECT Region, ROUND(AVG(GDP_USD_billion), 2)
        FROM (
            SELECT r.Region, g.GDP_USD_billion
            FROM Countries_by_GDP g
            JOIN Country_Region r ON g.Country = r.Country
            WHERE r.Region = 'Asia'
            ORDER BY g.GDP_USD_billion DESC
            LIMIT 5
        )
        UNION ALL
        SELECT Region, ROUND(AVG(GDP_USD_billion), 2)
        FROM (
            SELECT r.Region, g.GDP_USD_billion
            FROM Countries_by_GDP g
            JOIN Country_Region r ON g.Country = r.Country
            WHERE r.Region = 'Europe'
            ORDER BY g.GDP_USD_billion DESC
            LIMIT 5
        )
        UNION ALL
        SELECT Region, ROUND(AVG(GDP_USD_billion), 2)
        FROM (
            SELECT r.Region, g.GDP_USD_billion
            FROM Countries_by_GDP g
            JOIN Country_Region r ON g.Country = r.Country
            WHERE r.Region = 'Americas'
            ORDER BY g.GDP_USD_billion DESC
            LIMIT 5
        )
        UNION ALL
        SELECT Region, ROUND(AVG(GDP_USD_billion), 2)
        FROM (
            SELECT r.Region, g.GDP_USD_billion
            FROM Countries_by_GDP g
            JOIN Country_Region r ON g.Country = r.Country
            WHERE r.Region = 'Africa'
            ORDER BY g.GDP_USD_billion DESC
            LIMIT 5
        )
        UNION ALL
        SELECT Region, ROUND(AVG(GDP_USD_billion), 2)
        FROM (
            SELECT r.Region, g.GDP_USD_billion
            FROM Countries_by_GDP g
            JOIN Country_Region r ON g.Country = r.Country
            WHERE r.Region = 'Middle East'
            ORDER BY g.GDP_USD_billion DESC
            LIMIT 5
        )
        UNION ALL
        SELECT Region, ROUND(AVG(GDP_USD_billion), 2)
        FROM (
            SELECT r.Region, g.GDP_USD_billion
            FROM Countries_by_GDP g
            JOIN Country_Region r ON g.Country = r.Country
            WHERE r.Region = 'Oceania'
            ORDER BY g.GDP_USD_billion DESC
            LIMIT 5
        )
        ORDER BY 2 DESC
    """):
        print(row)

    conn.close()


# ============================================================
# Main
# ============================================================

if __name__ == "__main__":
    create_country_region_table()
    extract(
        "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29",
        RAW_JSON
    )
    transform(RAW_JSON, TRANSFORMED_JSON)
    load(TRANSFORMED_JSON)
    run_queries()